export const DATE_FORMAT_WITH_DASHES = 'yyyy-MM-dd'
export const DATE_FORMAT_WITH_SLASHES = 'yyyy/MM/dd'
export const TIME_FORMAT = 'HH:mm'
export const DATE_TIME_FORMAT = 'dd.MM.yyyy, HH:mm'
export const DATE_TIME_WITH_DOTS = 'dd.MM.yyyy'
